### ISSUE TITLE
Mock ups for dashboard showing dataset release status

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/release_administrator#2]
Similarly to the mock-ups for Release Administrator app, develop mock ups for a dashboard showing release status across datasets in a set of projects.

We'd need to decide if the dashboard belongs to the Release Administrator App (RAA) - likely yes?

Acceptance criteria: implementation ready mock ups for dashboard.

**Comment by ychae** [comment]
@milen-sage @lakikowolfe can you add me with write access to this repo?

**Comment by lakikowolfe** [comment]
Discussion of user scenarios [here](https://docs.google.com/document/d/1keStRC4kDpa6j0zKHOdnirAZUIiBpz9yuiP5UdBbLis/edit)

**Comment by lakikowolfe** [comment]
Mock ups in google slides [here](https://docs.google.com/presentation/d/1IbGZ3GrERepIXP44ltC909ZLrOtDy1kZAx0aUAXly54/edit?usp=sharing)

**Comment by ychae** [comment]
Depends on Brian's green light
